### ISSUE TITLE
`ox` import raises an exception

### ISSUE THREAD

**Issue by pareeohnos** [ib-ruby/ib-api#18]
This gem appears to depend on `ox` but for some reason it isn't being installed automatically. I recently installed the gem for a personal project, and upon installing it wrote a very simple bit of code literally just to connect to TWS and it raised an exception:

```
Traceback (most recent call last):
	24: from ./bin/tt:4:in `<main>'
	23: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	22: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	21: from /Users/myuser/Documents/Work/Personal/Trading/trade_tools/lib/main.rb:1:in `<top (required)>'
	20: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	19: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	18: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	17: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/ib-api-972.5/lib/ib-api.rb:7:in `<top (required)>'
	16: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	15: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	14: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/ib-api-972.5/lib/requires.rb:8:in `<top (required)>'
	13: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	12: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	11: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/ib-api-972.5/lib/ib/connection.rb:6:in `<top (required)>'
	10: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 9: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 8: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/ib-api-972.5/lib/ib/messages.rb:13:in `<top (required)>'
	 7: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 6: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 5: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/ib-api-972.5/lib/ib/messages/incoming.rb:1:in `<top (required)>'
	 4: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 3: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 2: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/ib-api-972.5/lib/ib/messages/incoming/abstract_message.rb:3:in `<top (required)>'
	 1: from /Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:117:in `require'
/Users/myuser/.asdf/installs/ruby/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:117:in `require': cannot load such file -- ox (LoadError)
```

Adding `ox` to my own Gemfile, or even just installing it with `gem install ox` makes it work, but shouldn't this get pulled in automatically?

**Comment by topofocus** [comment]
Thanks for reporting this.

Moved the ox-dependency from Gemfile to gemspec  (in the master-branche) 

This should cover this misbehavior and will be included in the gem-release

**Comment by pareeohnos** [comment]
Just installed from master branch and that works 🙂
